export const GET_STORED_ATTRIBUTES = "GET_STORED_ATTRIBUTES";
export const GET_STORED_ATTRIBUTES_SUCCESS = "GET_STORED_ATTRIBUTES_SUCCESS";
export const GET_STORED_ATTRIBUTES_FAILURE = "GET_STORED_ATTRIBUTES_FAILURE";

export const UPDATE_ATTRIBUTE_POOL = "UPDATE_ATTRIBUTE_POOL";

export const UPDATE_STORED_ATTRIBUTE_POOL = "UPDATE_STORED_ATTRIBUTE_POOL";
export const UPDATE_STORED_ATTRIBUTE_POOL_SUCCESS =
    "UPDATE_STORED_ATTRIBUTE_POOL_SUCCESS";
export const UPDATE_STORED_ATTRIBUTE_POOL_FAILURE =
    "UPDATE_STORED_ATTRIBUTE_POOL_FAILURE";
