export const OPEN_WISHLIST_MODAL = "OPEN_WISHLIST_MODAL";
export const CLOSE_WISHLIST_MODAL = "CLOSE_WISHLIST_MODAL";
export const SET_SELECTED_WISHLIST_ID = "SET_SELECTED_WISHLIST_ID";
export const SET_SHOW_WISHLIST_PRODUCTS = "SET_SHOW_WISHLIST_PRODUCTS";

export const SET_PRODUCTS_TO_SAVE_IN_WISHLIST =
	"SET_PRODUCTS_TO_SAVE_IN_WISHLIST";

export const IS_EDIT_WISHLIST = "IS_EDIT_WISHLIST";
export const IS_CREATE_WISHLIST = "IS_CREATE_WISHLIST";

// not to remove same products from favorites if it is not added in it at that time
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";

export const SET_SELECTED_COLLECTION_DATA = "SET_SELECTED_COLLECTION_DATA";
