export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const FETCH_CART = "FETCH_CART";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_FAILURE = "FETCH_CART_FAILURE";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE";

export const CREATE_LOYALTY_BADGE = "CREATE_LOYALTY_BADGE";
export const CREATE_LOYALTY_BADGE_SUCCESS = "CREATE_LOYALTY_BADGE_SUCCESS";
export const CREATE_LOYALTY_BADGE_FAILURE = "CREATE_LOYALTY_BADGE_FAILURE";

export const FETCH_EARNING_POINTS = "FETCH_EARNING_POINTS";
export const FETCH_EARNING_POINTS_SUCCESS = "FETCH_EARNING_POINTS_SUCCESS";
export const FETCH_EARNING_POINTS_FAILURE = "FETCH_EARNING_POINTS_FAILURE";
