export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const FETCH_CART = "FETCH_CART";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_FAILURE = "FETCH_CART_FAILURE";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE";

export const CREATE_LOYALTY_BADGE = "CREATE_LOYALTY_BADGE";
export const CREATE_LOYALTY_BADGE_SUCCESS = "CREATE_LOYALTY_BADGE_SUCCESS";
export const CREATE_LOYALTY_BADGE_FAILURE = "CREATE_LOYALTY_BADGE_FAILURE";

export const FETCH_EARNING_POINTS = "FETCH_EARNING_POINTS";
export const FETCH_EARNING_POINTS_SUCCESS = "FETCH_EARNING_POINTS_SUCCESS";
export const FETCH_EARNING_POINTS_FAILURE = "FETCH_EARNING_POINTS_FAILURE";

export const CHECKOUT_UPDATE_POINTS = "CHECKOUT_UPDATE_POINTS";
export const CHECKOUT_UPDATE_POINTS_SUCCESS = "CHECKOUT_UPDATE_POINTS_SUCCESS";
export const CHECKOUT_UPDATE_POINTS_FAILURE = "CHECKOUT_UPDATE_POINTS_FAILURE";

export const SEND_SESSION_HCS20_POINTS_SUCCESS =
  "SEND_SESSION_HCS20_POINTS_SUCCESS";
export const SEND_SESSION_HCS20_POINTS_FAILURE =
  "SEND_SESSION_HCS20_POINTS_FAILURE";

export const CHECK_SESSION_HCS20_POINTS_SUCCESS =
  "CHECK_SESSION_HCS20_POINTS_SUCCESS";
export const CHECK_SESSION_HCS20_POINTS_FAILURE =
  "CHECK_SESSION_HCS20_POINTS_FAILURE";

export const REDEEM_SESSION_HCS20_POINTS = "REDEEM_SESSION_HCS20_POINTS";
export const REDEEM_SESSION_HCS20_POINTS_SUCCESS =
  "REDEEM_SESSION_HCS20_POINTS_SUCCESS";
export const REDEEM_SESSION_HCS20_POINTS_FAILURE =
  "REDEEM_SESSION_HCS20_POINTS_FAILURE";

export const CLAIM_STORE_POINTS_SUCCESS = "CLAIM_STORE_POINTS_SUCCESS";
export const CLAIM_STORE_POINTS_FAILURE = "CLAIM_STORE_POINTS_FAILURE";
