export const APPLY_WISHLIST_PRODUCTS_FILTER = "APPLY_WISHLIST_PRODUCTS_FILTER";
export const RERUN_APPLY_WISHLIST_PRODUCTS_FILTER =
	"RERUN_APPLY_WISHLIST_PRODUCTS_FILTER";
export const APPLY_WISHLIST_PRODUCTS_FILTER_SUCCESS =
	"APPLY_WISHLIST_PRODUCTS_FILTER_SUCCESS";
export const APPLY_WISHLIST_PRODUCTS_FILTER_FAILURE =
	"APPLY_WISHLIST_PRODUCTS_FILTER_FAILURE";
export const APPLY_WISHLIST_PRODUCTS_FILTER_RESET =
	"APPLY_WISHLIST_PRODUCTS_FILTER_RESET";
export const REMOVE_PRODUCTS_FROM_APPLIED_FILTERS_USER_COLLECTION =
	"REMOVE_PRODUCTS_FROM_APPLIED_FILTERS_USER_COLLECTION";
