export const SET_USER_INFO = "SET_USER_INFO";
export const GET_USER_INFO_ASYNC = "GET_USER_INFO_ASYNC";
export const SET_USER_INFO_FETCHING = "SET_USER_INFO_FETCHING";

// action types for help me show modal
export const SET_HELP_ME_SHOP_MODAL_OPEN = "SET_HELP_ME_SHOP_MODAL_OPEN";
export const SET_HELP_ME_SHOP_MODAL_SHARED_LINK =
	"SET_HELP_ME_SHOP_MODAL_SHARED_LINK";

// action types for shared page recommendations
export const HANDLE_SHARED_PAGE_REC_PRODUCT_CLICK =
	"HANDLE_SHARED_PAGE_REC_PRODUCT_CLICK";
export const FETCH_SHARED_PAGE_RECOMMENDATIONS =
	"FETCH_SHARED_PAGE_RECOMMENDATIONS";
export const FETCH_SHARED_PAGE_RECOMMENDATIONS_SUCCESS =
	"FETCH_SHARED_PAGE_RECOMMENDATIONS_SUCCESS";
export const FETCH_SHARED_PAGE_RECOMMENDATIONS_FAILURE =
	"FETCH_SHARED_PAGE_RECOMMENDATIONS_FAILURE";
export const CLEAR_SHARED_PAGE_RECOMMENDATIONS_FAILURE =
	"CLEAR_SHARED_PAGE_RECOMMENDATIONS_FAILURE";

// shared page collections data
export const FETCH_SHARED_PAGE_COLLECTIONS = "FETCH_SHARED_PAGE_COLLECTIONS";
export const FETCH_SHARED_PAGE_COLLECTIONS_SUCCESS =
	"FETCH_SHARED_PAGE_COLLECTIONS_SUCCESS";
export const CLEAR_SHARED_PAGE_COLLECTIONS =
	"CLEAR_SHARED_PAGE_COLLECTIONS";
