export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILURE = "GET_USER_INFO_FAILURE";
export const SAVE_USER_INFO = "SAVE_USER_INFO";
export const IS_SAVING_USER_INFO = "IS_SAVING_USER_INFO";
export const GET_USER_COLLECTIONS = "GET_USER_COLLECTIONS";
export const GET_USER_COLLECTIONS_SUCCESS = "GET_USER_COLLECTIONS_SUCCESS";
export const GET_USER_COLLECTIONS_FAILURE = "GET_USER_COLLECTIONS_FAILURE";
export const GET_USER_COLLECTIONS_RESET = "GET_USER_COLLECTIONS_RESET";
export const GET_CREATOR_COLLECTIONS = "GET_CREATOR_COLLECTIONS";
export const GET_CREATOR_COLLECTIONS_SUCCESS = "GET_CREATOR_COLLECTIONS_SUCCESS";
export const GET_CREATOR_COLLECTIONS_FAILURE = "GET_CREATOR_COLLECTIONS_FAILURE";
export const GET_USER_COLLECTION = "GET_USER_COLLECTION";
export const GET_USER_COLLECTION_SUCCESS = "GET_USER_COLLECTION_SUCCESS";
export const GET_USER_COLLECTION_FAILURE = "GET_USER_COLLECTION_FAILURE";
export const GET_SINGLE_USER_COLLECTION = "GET_SINGLE_USER_COLLECTION";
export const GET_SINGLE_USER_COLLECTION_SUCCESS = "GET_SINGLE_USER_COLLECTION_SUCCESS";
export const GET_SINGLE_USER_COLLECTION_FAILURE = "GET_SINGLE_USER_COLLECTION_FAILURE";
export const GUEST_POPUP_SHOW = "GUEST_POPUP_SHOW"

export const REMOVE_PRODUCTS_FROM_USER_COLLECTIONS =
	"REMOVE_PRODUCTS_FROM_USER_COLLECTIONS";
export const SET_STARRED_USER_COLLECTIONS = "SET_STARRED_USER_COLLECTIONS";
export const SET_UPDATED_STATUS_USER_COLLECTIONS =
	"SET_UPDATED_STATUS_USER_COLLECTIONS";
export const REPLACE_SORTED_USER_COLLECTIONS =
	"REPLACE_SORTED_USER_COLLECTIONS ";
export const REPLACE_AND_UPDATE_USER_COLLECTION_DATA =
	"REPLACE_AND_UPDATE_USER_COLLECTION_DATA";
export const REMOVE_COLLECTION_FROM_USER_COLLECTIONS =
	"REMOVE_COLLECTION_FROM_USER_COLLECTIONS";
