export const SHOW_SIMILAR = "SHOW_SIMILAR";
export const FETCH_SIMILAR_PRODUCTS = "FETCH_SIMILAR_PRODUCTS";
export const FETCH_SIMILAR_PRODUCTS_SUCCESS = "FETCH_SIMILAR_PRODUCTS_SUCCESS";
export const FETCH_SIMILAR_PRODUCTS_FAILURE = "FETCH_SIMILAR_PRODUCTS_FAILURE";
