export const REORDER_WISHLIST = "REORDER_WISHLIST";
export const REORDER_WISHLIST_SUCCESS = "REORDER_WISHLIST_SUCCESS";
export const REORDER_WISHLIST_FAILURE = "REORDER_WISHLIST_FAILURE";
export const REORDER_WISHLIST_RESET = "REORDER_WISHLIST_RESET";
