export const CREATE_WISHLIST = "CREATE_WISHLIST";
export const CREATE_WISHLIST_SUCCESS = "CREATE_WISHLIST_SUCCESS";
export const CREATE_WISHLIST_FAILURE = "CREATE_WISHLIST_FAILURE";
export const CREATE_WISHLIST_RESET = "CREATE_WISHLIST_RESET";
