export const GET_INFLUENCER_INFO = "GET_INFLUENCER_INFO";
export const GET_INFLUENCER_INFO_SUCCESS = "GET_INFLUENCER_INFO_SUCCESS";
export const GET_INFLUENCER_INFO_FAILURE = "GET_INFLUENCER_INFO_FAILURE";

export const GET_INFLUENCER_COLLECTIONS = "GET_INFLUENCER_COLLECTIONS";
export const CLEAR_INFLUENCER_COLLECTIONS = "CLEAR_INFLUENCER_COLLECTIONS";
export const GET_INFLUENCER_COLLECTIONS_SUCCESS =
	"GET_INFLUENCER_COLLECTIONS_SUCCESS";
export const GET_INFLUENCER_COLLECTIONS_FAILURE =
	"GET_INFLUENCER_COLLECTIONS_FAILURE";

// single collection
export const GET_INFLUENCER_COLLECTION = "GET_INFLUENCER_COLLECTION";
export const GET_INFLUENCER_COLLECTION_SUCCESS =
	"GET_INFLUENCER_COLLECTION_SUCCESS";
export const GET_INFLUENCER_COLLECTION_FAILURE =
	"GET_INFLUENCER_COLLECTION_FAILURE";

export const REPLACE_AND_UPDATE_INFLUENCER_COLLECTION_DATA =
	"REPLACE_AND_UPDATE_INFLUENCER_COLLECTION_DATA";
