export const FETCH_CUSTOM_PRODUCTS = "CUSTOM_PRODUCTS/FETCH_CUSTOM_PRODUCTS";
export const FETCH_CUSTOM_PRODUCTS_SUCCESS =
	"CUSTOM_PRODUCTS/FETCH_CUSTOM_PRODUCTS_SUCCESS";
export const FETCH_CUSTOM_PRODUCTS_FAILURE =
	"CUSTOM_PRODUCTS/FETCH_CUSTOM_PRODUCTS_FAILURE";

export const REMOVE_CUSTOM_PRODUCTS = "CUSTOM_PRODUCTS/REMOVE_CUSTOM_PRODUCTS";
export const REMOVE_CUSTOM_PRODUCTS_SUCCESS =
	"CUSTOM_PRODUCTS/REMOVE_CUSTOM_PRODUCTS_SUCCESS";
export const REMOVE_CUSTOM_PRODUCTS_FAILURE =
	"CUSTOM_PRODUCTS/REMOVE_CUSTOM_PRODUCTS_FAILURE";
export const REMOVE_PRODUCTS_FROM_SAVED_CUSTOM_PRODUCTS =
	"CUSTOM_PRODUCTS/REMOVE_PRODUCTS_FROM_SAVED_CUSTOM_PRODUCTS";

export const UPDATE_CUSTOM_PRODUCTS = "CUSTOM_PRODUCTS/UPDATE_CUSTOM_PRODUCTS";
export const UPDATE_CUSTOM_PRODUCTS_SUCCESS =
	"CUSTOM_PRODUCTS/UPDATE_CUSTOM_PRODUCTS_SUCCESS";
export const UPDATE_CUSTOM_PRODUCTS_FAILURE =
	"CUSTOM_PRODUCTS/UPDATE_CUSTOM_PRODUCTS_FAILURE";
