export const OPEN_MENU_ITEM = "OPEN_MENU_ITEM";
export const FETCH_INFLUENCER_LIST = "FETCH_INFLUENCER_LIST";
export const FETCH_INFLUENCER_LIST_SUCCESS = "FETCH_INFLUENCER_LIST_SUCCESS";
export const FETCH_INFLUENCER_LIST_FAILURE = "FETCH_INFLUENCER_LIST_FAILURE";
export const SET_SHOW_PEOPLE = "SET_SHOW_PEOPLE";
