export const SHOW_CATEGORIES = "SHOW_CATEGORIES";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";
export const FETCH_CATEGORIES_RESET = "FETCH_CATEGORIES_RESET";

export const UPDATE_CATEGORIES_DATA_INFLUENCER_WIDGET_STARRED =
	"UPDATE_CATEGORIES_DATA_INFLUENCER_WIDGET_STARRED";

export const OPEN_MENU_ITEM = "OPEN_MENU_ITEM";
