export const SET_SOCKET_ID = "CHAT_V2/SET_SOCKET_ID";
export const SET_CHAT_MESSAGE = "CHAT_V2/SET_CHAT_MESSAGE";
export const SET_CHAT_IMAGE_URL = "CHAT_V2/SET_CHAT_IMAGE_URL"; // new format
export const SET_CHAT_MUTE = "CHAT_V2/SET_CHAT_MUTE";
export const SET_AURA_SPEAKING = "CHAT_V2/SET_AURA_SPEAKING";
export const SET_USER_DATA_SENT = "CHAT_V2/SET_USER_DATA_SENT";
export const SET_SHOW_CHAT_MODAL = "CHAT_V2/SET_SHOW_CHAT_MODAL";
export const SET_AURA_CHAT_SETTING = "CHAT_V2/SET_AURA_CHAT_SETTING";
export const SET_CHAT_SEARCH_TYPE = "CHAT_V2/SET_CHAT_SEARCH_TYPE";
export const SET_SHOW_CHAT_LOADER = "CHAT_V2/SET_SHOW_CHAT_LOADER";
export const SET_CHAT_GENERAL_SUGGESTIONS =
	"CHAT_V2/SET_CHAT_GENERAL_SUGGESTIONS";
export const SET_ACTIVE_SEARCH_OPTION = "CHAT_V2/SET_ACTIVE_SEARCH_OPTION"; // new format 
export const SET_AURA_HELPER_MESSAGE = "CHAT_V2/SET_AURA_HELPER_MESSAGE"; // new format
export const SET_AURA_SERVER_IMAGE = "CHAT_V2/SET_AURA_SERVER_IMAGE"; // new format
export const SET_CHAT_PRODUCTS = "CHAT_V2/SET_CHAT_PRODUCTS"; // new format
export const SET_CHAT_SHOP_A_LOOK = "CHAT_V2/SET_CHAT_SHOP_A_LOOK"; // new format
export const RESET_SUGGESTIONS_LIST = "CHAT_V2/RESET_SUGGESTIONS_LIST"; // new format
export const SET_SUGGESTIONS_LIST = "CHAT_V2/SET_SUGGESTIONS_LIST"; // new format
export const SET_SUGGESTIONS_PRODUCTS = "CHAT_V2/SET_SUGGESTIONS_PRODUCTS"; // new format
export const SET_RECOMMENDATION_PRODUCTS = "CHAT_V2/SET_RECOMMENDATION_PRODUCTS"; // new format
export const SET_MORE_PRODUCTS = "CHAT_V2/SET_MORE_PRODUCTS"; // new format
export const SET_OVERLAY_COORDINATES = "CHAT_V2/SET_OVERLAY_COORDINATES"; // new format

export const SET_SUGGESTIONS_PRODUCTS_FILTERS =
	"CHAT_V2/SET_SUGGESTIONS_PRODUCTS_FILTERS"; // new format
export const SET_SUGGESTIONS_PRODUCTS_IS_LOADING =
	"CHAT_V2/SET_SUGGESTIONS_PRODUCTS_IS_LOADING"; // new format
export const SET_SUGGESTIONS_SELECTED_TAG =
	"CHAT_V2/SET_SUGGESTIONS_SELECTED_TAG"; // new format
export const SET_RECOMMENDATION_SELECTED_TAG =
	"CHAT_V2/SET_RECOMMENDATION_SELECTED_TAG"; // new format
export const SET_MORESEARCH_SELECTED_TAG =
	"CHAT_V2/SET_MORESEARCH_SELECTED_TAG"; // new format
export const SET_SUGGESTIONS_SELECTED_ADDITIONAL_TAG =
	"CHAT_V2/SET_SUGGESTIONS_SELECTED_ADDITIONAL_TAG"; // new format
export const CLEAR_SUGGESTIONS_SELECTED_ADDITIONAL_TAG =
	"CHAT_V2/CLEAR_SUGGESTIONS_SELECTED_ADDITIONAL_TAG"; // new format
export const REMOVE_SUGGESTION_DATA_TAG = "CHAT_V2/REMOVE_SUGGESTION_DATA_TAG"; // new format
export const SET_SERVER_CHAT_MESSAGE = "CHAT_V2/SET_SERVER_CHAT_MESSAGE";
export const SET_CHAT_PRODUCTS_DATA = "CHAT_V2/SET_CHAT_PRODUCTS_DATA";
export const SET_WIDGET_HEADER = "CHAT_V2/SET_WIDGET_HEADER";
export const SET_WIDGET_IMAGE = "CHAT_V2/SET_WIDGET_IMAGE"; // new format
export const SET_CHAT_USER_ACTION = "CHAT_V2/SET_CHAT_USER_ACTION";
export const SET_SOCKET_EXCEPTION = "CHAT_V2/SET_SOCKET_EXCEPTION";
export const SET_SHOW_SOCKET_EXCEPTION = "CHAT_V2/SET_SHOW_SOCKET_EXCEPTION";
export const SET_SHOW_AURA_INTRO = "CHAT_V2/SET_SHOW_AURA_INTRO";
export const SET_AI_EXTRACTION_DATA = "CHAT_V2/SET_AI_EXTRACTION_DATA";
export const SET_IS_FRESH_SEARCH = "CHAT_V2/SET_IS_FRESH_SEARCH"; // new format
export const RESET_AURA_SEARCH_RESPONSE = "CHAT_V2/RESET_AURA_SEARCH_RESPONSE"; // new format
