export const VALIDATE_AND_SHOW_EARNED_NFT_REWARD =
	"VALIDATE_AND_SHOW_EARNED_NFT_REWARD";

export const CLAIM_EARNED_NFT_REWARD = "CLAIM_EARNED_NFT_REWARD";

export const CONNECT_VENLY_WALLET = "CONNECT_VENLY_WALLET";

export const SHOW_EARNED_REWARD_MODAL = "SHOW_EARNED_REWARD_MODAL";
export const CLOSE_EARNED_REWARD_MODAL = "CLOSE_EARNED_REWARD_MODAL";
