// import { isStagingEnv } from "./config";

// collection access
export const COLLECTION_PUBLIC = "public";
export const COLLECTION_PRIVATE = "private";

// collection status
export const COLLECTION_IN_PROGRESS = "in progress";
export const COLLECTION_DONE = "done";

// collection type
export const COLLECTION_TYPE_CUSTOM_PLIST = "custom_plist";
export const COLLECTION_TYPE_AUTO_PLIST = "auto_plist";
export const COLLECTION_TYPE_SYSTEM = "system";

// collection generated by
export const COLLECTION_GENERATED_BY_DESC_BASED = "desc_based";
export const COLLECTION_GENERATED_BY_BLOG_BASED = "blog_based";
export const COLLECTION_GENERATED_BY_VIDEO_BASED = "video_based";
export const COLLECTION_GENERATED_BY_PLIST_BASED = "plist_based";
export const COLLECTION_GENERATED_BY_IMAGE_BASED = "image_based";
export const COLLECTION_GENERATED_BY_SEARCH_BASED = "search_based";
export const COLLECTION_GENERATED_BY_MY_PRODUCTS_BASED = "my_products_based";

// ipp for shared page recommendations data
export const sharedPageRecommendationsIpp = 10;

// query param key for chat search text
export const PARAM_SEARCH_TEXT = "search_text";

// Sign In expires after days
export const SIGN_IN_EXPIRE_DAYS = 365;
export const GUESTSKIP_EXPIRE_HOURS = 1;

// keys for cookie
export const COOKIE_TT_ID = "tid";
export const COOKIE_EMAIL = "UN_email";
export const COOKIE_USER_TYPE = "UN_userType";
export const COOKIE_DEBUG_VIEW = "debugView";

// values for cookie
export const COOKIE_USER_TYPE_REGISTERED = "R";
export const COOKIE_USER_TYPE_GUEST = "G";
export const COOKIE_DEBUG_VIEW_ADMIN_VIEW = "adminView";
export const COOKIE_DEBUG_VIEW_GENERAL_VIEW = "generalView";

// debug local storage key
export const NEW_USER_LOCAL_STORAGE = "new_user";
export const LOCAL_STORAGE_USER_VISITED_CREATE_COLLECTION =
	"create_collection_visited";
export const LOCAL_STORAGE_S_ID = "tt_sid";
export const LOCAL_STORAGE_PREV_S_ID = "prev_tt_sid";
export const LOCAL_STORAGE_LOGGED_IN_USER_ID = "user_id";

// debug local storage value
export const DEBUG_LOCAL_STORAGE_UNTHINK = "unthink";

// feature flags cookie key
export const COOKIE_ENABLED_FEATURES = "enabled_features";

// feature flags cookie values
export const COOKIE_FEATURE_FETCH_MORE = "fetch_more";
export const COOKIE_FEATURE_CATEGORY_TAGS = "category_tags";

// send message with prefix to socket based on the user interaction with mic or manual typing
export const SEND_MESSAGE_WITH_PREFIX_SS_KEY = "unsmwp";
export const SOCKET_MESSAGE_PREFIX_MESSAGE = ""; // previously it was set to "find "

// default influencer code
export const DEFAULT_INFLUENCER_CODE = "UTH-DIRECT";

//chat user actions
export const AURA_CLICK = "aura_click";

//menu items
export const CATEGORIES = "categories";
export const PEOPLE = "people";
export const EARN_REWARDS = "earn_rewards";

// routes constants
export const MY_PROFILE = "/my-profile";
export const PATH_CREATE_COLLECTION = "/create-collection";
export const PATH_BLOG = "/blog";
export const PATH_SIGN_IN = "/signin";
export const PROFILE = "/profile/";
export const INFLUENCER = "/influencer";
export const INFLUENCER_SHARED = "/influencer/shared";
export const PATH_STORE = "/store";
export const PATH_ROOT = "/";
export const COLLECTION = "/collections/";
export const WELCOME = "/welcome/";
export const CREATE_STORE = "/create-store/";
export const ROUTES = {
	ROOT: "/",
	STORE_PAGE: "/store/",
	SIGN_IN_PAGE: "/signin/",
	SIGN_UP_PAGE: "/signup/",
	TRY_FOR_FREE_PAGE: "/try-for-free/",
	UPDATE_PROFILE: "/profile/",
	WELCOME: "/welcome/",
	MY_PRODUCTS: "/my-products",
	AURA_SEARCH_PAGE: "/aura-search/[store_name]",
};
export const COLLECTIONS_ID = "collections"; // id for all collections page
export const ERAS_COLLECTIONS_ID = "eras-collections"; // id for swiftly styled eras collections
export const ERAS_FEATURED_COLLECTIONS_ID = "featured-collections"; // id for swiftly styled featured collections

// modal's z-indexes
export const SIMILAR_MODAL_Z_INDEX = "100";
export const WISHLIST_MODAL_Z_INDEX = "150";
export const HEADER_Z_INDEX = "50"; //given with tailwind class

export const WISHLIST_TITLE = "Collection";
export const WISHLISTS_TITLE = "Collections";

export const TAG_TITLE = "keyword";
export const TAGS_TITLE = "keywords";

export const collectionPlistIPP = 20;
export const FETCH_COLLECTIONS_PRODUCT_LIMIT = 12;
export const COLLECTION_PRODUCTS_FETCH_IPP = 30;

// blog collection page status
export const IN_PROGRESS = "in progress";
export const DONE = "done";
export const PUBLISHED = "published";

// collection page cover image sizings
export const COLLECTION_COVER_IMG_SIZE_900_900 = "900X900";
export const COLLECTION_COVER_IMG_SIZE_340_340 = "340X340";
export const COLLECTION_COVER_IMG_SIZE_220_220 = "220X220";
export const COLLECTION_COVER_IMG_SIZES = [
	COLLECTION_COVER_IMG_SIZE_900_900,
	COLLECTION_COVER_IMG_SIZE_340_340,
	COLLECTION_COVER_IMG_SIZE_220_220,
];

// profile page cover image sizings
export const PROFILE_COVER_IMG_SIZES = "1200X320";

export const btHeaderOptions = {
	clubdiscounts: " https://www.budgettravel.com/clubdiscounts",
	discoverusa: "https://www.budgettravel.com/discoverusa",
	deals: "https://www.budgettravel.com/deals",
	sweepstakes: "https://www.budgettravel.com/sweepstakes",
	shop: "https://shop.budgettravel.com",
	explore: "https://www.budgettravel.com/explore",
	myaccount: "https://www.budgettravel.com/myaccount",
	search: "https://www.budgettravel.com/search",
};

export const SUPER_ADMIN = "super_admin";

export const favorites_collection_name = "Editor’s Picks";

export const category_widget_type_suggestion_chip = "suggestion_chip";
export const category_widget_type_influencer_widget = "influencer_widget";
export const category_widget_type_super_admin_seller_widget =
	"super_admin_seller_widget";

export const API_STATUS_SUCCESS = 200;

export const defaultFavoriteColl = {
	collection_name: "favorites",
	type: COLLECTION_TYPE_SYSTEM,
	product_lists: [],
	status: PUBLISHED,
};

export const myProductsColl = {
	collection_name: "My products",
	// type: COLLECTION_TYPE_SYSTEM,
	// product_lists: [],
	// status: PUBLISHED,
};

export const ERR_CODE_USER_NOT_VERIFIED = "USER_NOT_VERIFIED";
export const ERR_CODE_USER_ALREADY_REGISTERED = "USER_ALREADY_REGISTERED";

// store user name
export const STORE_USER_NAME_BUDGETTRAVEL = "budgettravel";
export const STORE_USER_NAME_SANTHAY = "santhay";
export const STORE_USER_NAME_HOMECENTRE = "homecentre";
export const STORE_USER_NAME_FASHIONDEMO = "fashiondemo";
export const STORE_USER_NAME_GOLDSURA = "goldsutra";
export const STORE_USER_NAME_SAMSKARA = "samskara";
export const STORE_USER_NAME_HEROESVILLAINS = "heroesvillains";
export const STORE_USER_NAME_SWIFTLYSTYLED = "swiftlystyled";
export const STORE_USER_NAME_DOTHELOOK = "dothelook";

// store display name
export const STORE_DISPLAY_NAME = {
	[STORE_USER_NAME_BUDGETTRAVEL]: "Budget Travel",
	[STORE_USER_NAME_SANTHAY]: "Santhay",
	[STORE_USER_NAME_HOMECENTRE]: "Homecentre",
	[STORE_USER_NAME_FASHIONDEMO]: "Fashion Demo",
};

// collection flow publishing options
export const PUBLISHING_OPTION_PAGE = "page";
export const PUBLISHING_OPTION_EXPORT_PRODUCTS_CSV = "export_products_csv";

//online selling platforms for seller
export const ONLINE_SELLING_PLATFORM_SHOPIFY = "shopify";
export const ONLINE_SELLING_PLATFORM_WOO_COMMERCE = "woo commerce";

// app message modal types
export const APP_MESSAGE_MODAL_TYPES = {
	DEFAULT: "DEFAULT",
};

// earned reward modal types
export const EARNED_REWARD_MODAL_TYPES = {
	DEFAULT: "DEFAULT",
	LEVEL_1_NFT: "level 1",
};

export const EARNED_NFT_STATUSES = {
	EARNED: "earned",
	TRANSFERRED: "transferred",
};

export const EARNED_NFT_NAMES = {
	[EARNED_REWARD_MODAL_TYPES.LEVEL_1_NFT]: "Unthink Creator",
};

export const EARNED_NFT_NAMES_TO_SHOW = {
	[EARNED_REWARD_MODAL_TYPES.LEVEL_1_NFT]: "an Unthink Creator",
};

export const EARNED_NFT_DESCRIPTIONS = {
	[EARNED_REWARD_MODAL_TYPES.LEVEL_1_NFT]:
		"Joined the Unthink creator community",
};

export const templatesLabelToShow = {
	// aura_ctl_desc: "Complete the look description template",
	// aura_ctl_tags: "Complete the look tags template",
	// aura_ss_desc: "Smart search description template",
	// aura_ss_tags: "Smart search tags template",
	// aura_stl_desc: "Shop the look description template",
	// aura_stl_tags: "Shop the look tags template",
	// aura_template_desc:""
	// aura_template_tags:""
	// blog_tag_template: "Blog collection tags template",
	// cc_template_desc: "Scratch collection description template",
	// cc_template_tags: "Scratch collection tags template",
	// cc_video_desctags: "Video collection video template",
	// cc_video_tagmap: ""
	// image_cc_template: "Image collection tags template",
	// image_ctl_aura: "Complete the look image template",
	// image_description_template:""
	// image_stl_aura: "Shop the look image template",
	// image_to_text_prompt:""
	// video_tags_template: "Video collection tags template",
	cc_text: "Collection text template",
	cc_image: "Collection image template",
	cc_blog: "Collection blog template",
	cc_video: "Collection video template",
	cc_shortvideo: "Collection short video template",
	aura_text_ss: "Smart search text template",
	aura_text_stl: "Shop the look text template",
	aura_text_ctl: "Complete the look text template",
	aura_image_ctl: "Complete the look image template",
	aura_image_stl: "Shop the look image template",
};

// export const STAGING_DEFAULT_AURA_SETTING = {
// 	aura_template_tags: `Create up to 15 comma-separated product related keywords or tags related to {query} by taking all the context from the {longdescription}. The keywords must have a maximum of 2 words in each item. Do not give vague keywords. Keywords are mandated to denote physical, real-world products. Make sure the keywords are seperated by comma and do not number the keywords. Do not give vague keywords. Do not include '\n' in the output. Do not repeat the keywords. Make sure the keywords don't start with e-commerce or online.`,
// 	aura_template_desc: `Please generate a concise summary comprising four to five sentences based on the {userdescription}. Make sure you are giving a response to the user. You are not an AI language model, so do not give responses like 'as an AI language model'. If you cannot understand the {userdescription} then you say It looks like you are searching for something. At the end of the sentence add this sentence 'Choose the products that match your preferences.'`,
// 	cc_template_tags: `Create up to 15 comma-separated product related keywords or tags related to {query} by taking all the context from the {longdescription}. The keywords must have a maximum of 2 words in each item. Do not give vague keywords. Keywords are mandated to denote physical, real-world products. Do not use '\n' in the output. Do not number the keywords. Do not repeat the keywords. Make sure the keywords don't start with e-commerce or online.`,
// 	cc_template_desc: `Please generate a 6-7 sentences based on the {userdescription}. Add <br> after every sentence in the output. Make sure you are giving a response to the user. You are not an AI language model, so do not give responses like 'as an AI language model'. if '#' is used in {userdescription} give more importance to the words after '#'. Do not add '#' in the output. In the starting of the output direct come to the point.`,
// 	blog_tag_template: `Create up to 12-15 comma-separated product related keywords or tags based on the {blog_content}. The keywords must have a maximum of 2 words in each item. Do not give vague keywords. Keywords are mandated to denote physical, real-world products. Make sure the keywords are seperated by comma and do not number the keywords. Do not give vague keywords. Do not include '\n' in the output. Do not repeat the keywords. Make sure the keywords don't start with e-commerce or online.`,
// 	video_tags_template: `Create up to 12-15 comma-separated product related keywords or tags from the given text:{video_text}. The keywords must have a maximum of 2 words in each item. Do not give vague keywords. Keywords are mandated to denote physical, real-world products. Make sure the keywords are seperated by comma and do not number the keywords. Do not give vague keywords. Do not include '\n' in the output. Do not repeat the keywords. Make sure the keywords don't start with e-commerce or online.`,
// };

// export const FINAL_DEFAULT_AURA_SETTING = {
// 	aura_template_tags: `Create up to 15 comma-separated product related keywords or tags related to {query} by taking all the context from the {longdescription}. The keywords must have a maximum of 2 words in each item. Do not give vague keywords. Keywords are mandated to denote physical, real-world products. Make sure the keywords are seperated by comma and do not number the keywords. Do not give vague keywords. Do not include '\n' in the output. Do not repeat the keywords. Make sure the keywords don't start with e-commerce or online.`,
// 	aura_template_desc: `Please generate a concise summary comprising four to five sentences based on the {userdescription}. Make sure you are giving a response to the user. You are not an AI language model, so do not give responses like 'as an AI language model'. If you cannot understand the {userdescription} then you say It looks like you are searching for something. At the end of the sentence add this sentence 'Choose the products that match your preferences.'`,
// 	cc_template_tags: `Create up to 15 comma-separated product related keywords or tags related to {query} by taking all the context from the {longdescription}. The keywords must have a maximum of 2 words in each item. Do not give vague keywords. Keywords are mandated to denote physical, real-world products. Do not use '\n' in the output. Do not number the keywords. Do not repeat the keywords. Make sure the keywords don't start with e-commerce or online.`,
// 	cc_template_desc: `Please generate a 6-7 sentences based on the {userdescription}. Add <br> after every sentence in the output. Make sure you are giving a response to the user. You are not an AI language model, so do not give responses like 'as an AI language model'. if '#' is used in {userdescription} give more importance to the words after '#'. Do not add '#' in the output. In the starting of the output direct come to the point.`,
// 	blog_tag_template: `Create up to 12-15 comma-separated product related keywords or tags based on the {blog_content}. The keywords must have a maximum of 2 words in each item. Do not give vague keywords. Keywords are mandated to denote physical, real-world products. Make sure the keywords are seperated by comma and do not number the keywords. Do not give vague keywords. Do not include '\n' in the output. Do not repeat the keywords. Make sure the keywords don't start with e-commerce or online.`,
// 	video_tags_template: `Create up to 12-15 comma-separated product related keywords or tags from the given text:{video_text}. The keywords must have a maximum of 2 words in each item. Do not give vague keywords. Keywords are mandated to denote physical, real-world products. Make sure the keywords are seperated by comma and do not number the keywords. Do not give vague keywords. Do not include '\n' in the output. Do not repeat the keywords. Make sure the keywords don't start with e-commerce or online.`,
// };

// export const DEFAULT_AURA_SETTING =
// 	process.env.NEXT_PUBLIC_STAGING_ENV === "true" // isStagingEnv
// 		? STAGING_DEFAULT_AURA_SETTING
// 		: FINAL_DEFAULT_AURA_SETTING;

export const CHAT_SEARCH_TYPES = {
	AURA: "AURA",
	SEARCH: "SEARCH",
	CAMERA: "CAMERA",
};

export const WIDGET_TYPE_Q_AND_A = "QandA";

export const CHAT_TYPE_CHAT = "CHAT";
export const CHAT_TYPE_QANDACHAT = "QANDACHAT";

export const CHAT_TYPES_KEYS = {
	[CHAT_TYPE_CHAT]: {
		chatMessage: "chatMessage",
		chatImageUrl: "chatImageUrl",
		showChatLoader: "showChatLoader",
		products: "products",
		shopALook: "shopALook",
	},
	[CHAT_TYPE_QANDACHAT]: {
		chatMessage: "qAndAChatMessage",
		showChatLoader: "qAndAShowChatLoader",
		products: "qAndAProducts",
	},
};

export const CHAT_SEARCH_OPTION_ID = {
	smart_search: "smart_search",
	shop_a_look: "shop_a_look",
	complete_the_look: "complete_the_look",
	product_search: "product_search",
	trending_collections: "trending_collections",
};

export const PRODUCT_DUMMY_URL = "dummy_url";

export const CURRENCY_INR = "INR";
export const CURRENCY_USD = "USD";

export const CURRENCY_SYMBOLS = {
	[CURRENCY_INR]: "&#8377;",
	[CURRENCY_USD]: "&#36;",
};

// upload products mode for my collection
export const UPLOAD_PRODUCT_MODE_IMAGES = "images";
export const UPLOAD_PRODUCT_MODE_CSV = "csv";

//ipp for custom products data
export const CUSTOM_PRODUCTS_FETCH_IPP = "100";

export const PRODUCT_SORT_OPTIONS = [
	{
		id: "Recommended",
		product_sort_by: "",
		product_sort_order: "",
	},
	{
		id: "Price: High To Low",
		product_sort_by: "price",
		product_sort_order: "desc",
	},
	{
		id: "Price: Low To High",
		product_sort_by: "price",
		product_sort_order: "asc",
	},
	{
		id: "Availability",
		product_sort_by: "avlble",
		product_sort_order: "desc",
	},
	{
		id: "Discount: High To Low",
		product_sort_by: "discount",
		product_sort_order: "desc",
	},
	{
		id: "Discount: Low To High",
		product_sort_by: "discount",
		product_sort_order: "asc",
	}
];

export const PRODUCT_SORT_OPTIONS_MY_PRODUCTS = [
	{
		id: "Recommended",
		product_sort_by: "created_on",
		product_sort_order: "desc",
	},
	{
		id: "Name",
		product_sort_by: "name",
		product_sort_order: "asc",
	},
	{
		id: "Price: High To Low",
		product_sort_by: "price",
		product_sort_order: "desc",
	},
	{
		id: "Price: Low To High",
		product_sort_by: "price",
		product_sort_order: "asc",
	},
	{
		id: "Availability",
		product_sort_by: "avlble",
		product_sort_order: "desc",
	},
	{
		id: "Discount",
		product_sort_by: "discount",
		product_sort_order: "desc",
	},
	{
		id: "Discount: High To Low",
		product_sort_by: "discount",
		product_sort_order: "desc",
	},
	{
		id: "Discount: Low To High",
		product_sort_by: "discount",
		product_sort_order: "asc",
	}
];

// user action for collection
export const EDIT_ACTION = "edit_action";
export const CREATE_ACTION = "create_action";

// links of main site
export const MAIN_SITE_URL = {
	[STORE_USER_NAME_SAMSKARA]: "https://www.samskarahome.com/",
	[STORE_USER_NAME_HEROESVILLAINS]: "https://heroesvillains.com/",
	[STORE_USER_NAME_BUDGETTRAVEL]: "https://www.budgettravel.com/",
};

// export const BRANDS_CONTACT_DETAILS = {
// 	arupa925: {
// 		title: "Jyothi Hattarki",
// 		email: "Arupa925silverjewelry@gmail.com",
// 		contact: "468-450-5040",
// 		couponCode: "ARUPA925-SAN-10P",
// 		brandName: "Arupa",
// 		brandDescription:
// 			"Arupa Jewellery Seller is a popular retailer specializing in exquisite jewelry pieces.  They offer a wide range of stunning and unique designs to cater to different tastes and preferences. Shopping at Arupa Jewellery Seller guarantees a delightful experience and the chance to own a timeless piece of beauty ",
// 	},
// 	varnah: {
// 		title: "Varnah Collection",
// 		email: "varnahsarees@gmail.com",
// 		contact: "913-262-4255",
// 		info: "Available to ship within USA",
// 		couponCode: "VARNAHSAREES-SAN-5P",
// 		brandName: "Varnah",
// 		brandDescription:
// 			"Varnah Jewelry is a renowned seller of exquisite jewelry pieces.  With their attention to detail and craftsmanship, Varnah Jewelry creates unique and stunning pieces that are perfect for any occasion.  Their collection features a mix of traditional and contemporary designs, catering to different tastes and preferences.",
// 	},
// };
