export const GET_COLLECTIONS_ASYNC = "GET_COLLECTIONS_ASYNC";
export const SET_COLLECTION_DETAILS = "SET_COLLECTION_DETAILS";
export const SET_COLLECTION_DETAILS_FETCHING =
	"SET_COLLECTION_DETAILS_FETCHING";
export const SET_SHOW_GALLERY = "SET_SHOW_GALLERY";
export const SET_SELECTED_COLLECTION = "SET_SELECTED_COLLECTION";
export const UPDATE_RECENTLY_VIEWED_LIST = "UPDATE_RECENTLY_VIEWED_LIST";
export const SET_COLLECTION_PRODUCT_CODES = "SET_COLLECTION_PRODUCT_CODES";
export const SET_COLLECTION_PRODUCTS = "SET_COLLECTION_PRODUCTS";
export const SET_COLLECTION_PRODUCTS_FETCHING =
	"SET_COLLECTION_PRODUCTS_FETCHING";
export const GET_COLLECTION_PRODUCTS_ASYNC = "GET_COLLECTION_PRODUCTS_ASYNC";
export const SET_COLLECTION_TITLE = "SET_COLLECTION_TITLE";
export const SET_SHOW_COLLECTION = "SET_SHOW_COLLECTION";
export const CREATE_COLLECTIONS_ASYNC = "CREATE_COLLECTIONS_ASYNC";
export const SET_CREATING_COLLECTION = "SET_CREATING_COLLECTION";
export const ADD_TO_COLLECTIONS_ASYNC = "ADD_TO_COLLECTIONS_ASYNC";
export const DELETE_COLLECTIONS_ASYNC = "DELETE_COLLECTIONS_ASYNC";
export const UPDATE_COLLECTIONS_STATUS = "UPDATE_COLLECTIONS_STATUS";
export const SET_SELECTED_COLLECTION_ID = "SET_SELECTED_COLLECTION_ID";
export const REMOVE_FROM_COLLECTIONS_ASYNC = "REMOVE_FROM_COLLECTIONS_ASYNC";
export const SET_PRODUCT_TO_SAVE_AFTER_COLLECTION_CREATED =
	"SET_PRODUCT_TO_SAVE_AFTER_COLLECTION_CREATED";
export const SET_SHOW_COLLECTION_MODAL = "SET_SHOW_COLLECTION_MODAL";
export const SET_ADDING_COLLECTION = "SET_ADDING_COLLECTION";
export const ADD_MFRCODE_TO_COLLECTIONS = "ADD_MFRCODE_TO_COLLECTIONS";
export const SET_COLLECTION_FOR_EDIT = "SET_COLLECTION_FOR_EDIT";
export const EDIT_COLLECTION = "EDIT_COLLECTION";
