export const DELETE_WISHLIST = "DELETE_WISHLIST";
export const DELETE_WISHLIST_SUCCESS = "DELETE_WISHLIST_SUCCESS";
export const DELETE_WISHLIST_FAILURE = "DELETE_WISHLIST_FAILURE";
export const DELETE_WISHLIST_RESET = "DELETE_WISHLIST_RESET";
