export const UPDATE_WISHLIST = "UPDATE_WISHLIST";
export const UPDATE_WISHLIST_SUCCESS = "UPDATE_WISHLIST_SUCCESS";
export const UPDATE_WISHLIST_FAILURE = "UPDATE_WISHLIST_FAILURE";
export const UPDATE_WISHLIST_RESET = "UPDATE_WISHLIST_RESET";
